# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fintech-fab.dev"
  config.vm.box_url = "http://fintech-fab.ru/files/fintech-fab.lts.64.box"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080
end
